import express from 'express'; import cors from 'cors'; import session from 'express-session'; import { randomUUID } from 'crypto'; import { OAuth2Client } from 'google-auth-library';
import { createBullBoard } from '@bull-board/api'; import { BullMQAdapter } from '@bull-board/api/bullMQAdapter'; import { ExpressAdapter } from '@bull-board/express';
import { config } from './config'; import { db, EmailRow } from './db'; import { emailQueue } from './queue'; import { indexEmail, searchIds } from './search'; import './worker';
declare module 'express-session' { interface SessionData { tenantId?:string; oauthState?:string; slackState?:string; } }
const app=express(); app.use(cors({origin:config.webUrl,credentials:true})); app.use(express.json({limit:'2mb'})); app.use(session({secret:config.sessionSecret,resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax'}}));
const boardAdapter=new ExpressAdapter(); boardAdapter.setBasePath('/admin/queues'); createBullBoard({queues:[new BullMQAdapter(emailQueue)],serverAdapter:boardAdapter}); app.use('/admin/queues',boardAdapter.getRouter());
const required=(req:any,res:any,next:any)=>req.session.tenantId?next():res.status(401).json({error:'Authentication required'});
app.get('/health',(_req,res)=>res.json({ok:true}));
app.get('/auth/google',(req,res)=>{ if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET)return res.status(501).json({error:'Set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET'}); const client=new OAuth2Client(process.env.GOOGLE_CLIENT_ID,process.env.GOOGLE_CLIENT_SECRET,process.env.GOOGLE_CALLBACK_URL); const state=randomUUID(); req.session.oauthState=state; res.redirect(client.generateAuthUrl({access_type:'offline',scope:['openid','email','profile'],state})); });
app.get('/auth/google/callback',async(req,res,next)=>{ try { if(req.query.state!==req.session.oauthState) throw new Error('Invalid OAuth state'); const client=new OAuth2Client(process.env.GOOGLE_CLIENT_ID,process.env.GOOGLE_CLIENT_SECRET,process.env.GOOGLE_CALLBACK_URL); const {tokens}=await client.getToken(String(req.query.code)); const ticket=await client.verifyIdToken({idToken:tokens.id_token!,audience:process.env.GOOGLE_CLIENT_ID}); const p=ticket.getPayload()!; const {rows}=await db.query('INSERT INTO tenants(id,email,name,avatar_url) VALUES($1,$2,$3,$4) ON CONFLICT(email) DO UPDATE SET name=EXCLUDED.name,avatar_url=EXCLUDED.avatar_url RETURNING id',[randomUUID(),p.email,p.name ?? p.email,p.picture ?? null]); req.session.tenantId=rows[0].id; res.redirect(config.webUrl); } catch(e){next(e);} });
app.post('/auth/logout',(req,res)=>req.session.destroy(()=>res.status(204).end()));
app.get('/api/me',required,async(req:any,res)=>{const {rows}=await db.query('SELECT id,email,name,avatar_url,slack_access_token IS NOT NULL AS slack_connected FROM tenants WHERE id=$1',[req.session.tenantId]);res.json(rows[0]);});
app.get('/auth/slack',required,(req:any,res)=>{if(!process.env.SLACK_CLIENT_ID)return res.status(501).json({error:'Set Slack OAuth credentials'});const state=randomUUID();req.session.slackState=state;const u=new URL('https://slack.com/oauth/v2/authorize');u.searchParams.set('client_id',process.env.SLACK_CLIENT_ID);u.searchParams.set('scope','chat:write');u.searchParams.set('redirect_uri',process.env.SLACK_CALLBACK_URL!);u.searchParams.set('state',state);res.redirect(u.toString());});
app.get('/auth/slack/callback',required,async(req:any,res,next)=>{try{if(req.query.state!==req.session.slackState)throw Error('Invalid OAuth state');const body=new URLSearchParams({client_id:process.env.SLACK_CLIENT_ID!,client_secret:process.env.SLACK_CLIENT_SECRET!,code:String(req.query.code),redirect_uri:process.env.SLACK_CALLBACK_URL!});const r:any=await fetch('https://slack.com/api/oauth.v2.access',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const d=await r.json();if(!d.ok)throw Error(d.error);await db.query('UPDATE tenants SET slack_access_token=$1,slack_team_id=$2 WHERE id=$3',[d.access_token,d.team?.id,req.session.tenantId]);res.redirect(config.webUrl);}catch(e){next(e)}});
app.post('/api/emails/schedule',required,async(req:any,res,next)=>{try { const {recipients,subject,body,sender,startsAt,delayMs=0,hourlyLimit=config.hourlyLimit}=req.body; if(!Array.isArray(recipients)||!recipients.length||!subject||!body||!sender||!startsAt) return res.status(400).json({error:'recipients, subject, body, sender, startsAt are required'}); const base=new Date(startsAt).getTime(), limit=Number(hourlyLimit); if(Number.isNaN(base)||!Number.isInteger(limit)||limit<1)return res.status(400).json({error:'Invalid start time or hourly limit'}); const created=[]; for(const [i,recipient] of recipients.entries()){const id=randomUUID(), scheduledAt=new Date(base+i*Number(delayMs)); const {rows:[email]}=await db.query<EmailRow>('INSERT INTO emails(id,tenant_id,recipient,subject,body,sender,hourly_limit,scheduled_at,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[id,req.session.tenantId,recipient,subject,body,sender,limit,scheduledAt,'scheduled']); const job=await emailQueue.add('send',{emailId:id},{jobId:id,delay:Math.max(0,scheduledAt.getTime()-Date.now())}); await db.query('UPDATE emails SET bull_job_id=$1 WHERE id=$2',[String(job.id),id]); await indexEmail(email); created.push(email);} res.status(201).json({count:created.length,emails:created}); }catch(e){next(e)}});
app.get('/api/emails',required,async(req:any,res,next)=>{try{const status=req.query.status as string|undefined,q=String(req.query.q??'');const ids=q?await searchIds(req.session.tenantId,q):null;let sql='SELECT * FROM emails WHERE tenant_id=$1';const vals:any[]=[req.session.tenantId];if(status){vals.push(status);sql+=` AND status=$${vals.length}`};if(ids){if(!ids.length)return res.json([]);vals.push(ids);sql+=` AND id=ANY($${vals.length})`}else if(q){vals.push(`%${q}%`);sql+=` AND (recipient ILIKE $${vals.length} OR subject ILIKE $${vals.length} OR body ILIKE $${vals.length})`}sql+=' ORDER BY scheduled_at DESC LIMIT 200';const {rows}=await db.query<EmailRow>(sql,vals);res.json(rows)}catch(e){next(e)}});
app.use((err:any,_req:any,res:any,_next:any)=>{console.error(err);res.status(500).json({error:err.message??'Internal server error'})}); app.listen(config.port,()=>console.log(`API: http://localhost:${config.port}; queues: /admin/queues`));
